# Generated by Django 4.0.4 on 2022-05-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
