# Generated by Django 4.0.4 on 2022-05-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(help_text='Area Located in Town', max_length=50)),
                ('ratings', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('image_url', models.URLField()),
                ('image_url1', models.URLField(default='', null=True)),
                ('image_url2', models.URLField(default='', null=True)),
                ('price', models.PositiveIntegerField()),
                ('agent', models.CharField(default='', max_length=30)),
                ('town', models.CharField(help_text='The town where the property is located', max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('units_available', models.IntegerField()),
                ('features', models.CharField(default='', max_length=500)),
                ('requirement', models.CharField(default='', max_length=750)),
            ],
            options={
                'ordering': ['units_available'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('R_type', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='reserved',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('r_id', models.CharField(max_length=10)),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('date_reserved', models.DateField(auto_now_add=True, null=True, verbose_name='date reserved')),
                ('repetitioncheck', models.CharField(default='', max_length=70, unique_for_date=models.DateField(auto_now_add=True, null=True, verbose_name='date reserved'))),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingApp.listing')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingApp.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='house_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostelT', to='housingApp.roomtype'),
        ),
        migrations.AddField(
            model_name='listing',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lords', to='housingApp.landlord'),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('Amount_paid', models.IntegerField()),
                ('payment_code', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingApp.reserved')),
            ],
        ),
    ]
