# Generated by Django 4.0.4 on 2022-05-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('R_type', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(help_text='Area Located in Town', max_length=50)),
                ('ratings', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('image_url', models.URLField()),
                ('image_url1', models.URLField(default='', null=True)),
                ('image_url2', models.URLField(default='', null=True)),
                ('price', models.PositiveIntegerField()),
                ('agent', models.CharField(default='', max_length=30)),
                ('town', models.CharField(help_text='The town where the property is located', max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('units_available', models.IntegerField()),
                ('features', models.CharField(default='', max_length=500)),
                ('requirement', models.CharField(default='', max_length=750)),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostelT', to='housingApp.roomtype')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lords', to='housingApp.landlord')),
            ],
            options={
                'ordering': ['units_available'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmedBookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('Amount_paid', models.IntegerField()),
                ('payment_code', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingApp.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingApp.listing'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingApp.roomtype'),
        ),
    ]
