# Generated by Django 4.0.4 on 2022-05-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserved',
            name='price',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='repetitioncheck',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
