# Generated by Django 4.0.4 on 2022-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ratings',
            field=models.IntegerField(),
        ),
    ]
