# Generated by Django 4.0.4 on 2022-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingApp', '0002_reserved_price_alter_reserved_repetitioncheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved',
            name='r_id',
            field=models.IntegerField(),
        ),
    ]
