# Generated by Django 4.0.4 on 2022-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingApp', '0003_listing_agent_listing_features_listing_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url1',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url2',
            field=models.URLField(default='', null=True),
        ),
    ]
