# Generated by Django 4.0.4 on 2022-05-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingApp', '0004_remove_reserved_r_id_reserved_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='confirmed'),
        ),
    ]
